package com.anshul.simplechatserver;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class User implements Serializable {
    private static final long serialVersionUID = 1L;
    private long userId; // unique identifier for the user (generated by server
			 // during registration)
    private String userEmail; // email for user
    private String userName; // name for user
    private String passwordHash; // hash of the user's password
    private Date lastSeen;

    private List<User> contacts;

    public User(long userId, String email, String name, String hash) {
	this.userId = userId;
	this.userEmail = email;
	this.userName = name;
	this.passwordHash = hash;
    }

    public void setLastSeen(Date time) {
	this.lastSeen = time;
    }

    public Date getLastSeen() {
	return this.lastSeen;
    }

    public long getUserId() {
	return this.userId;
    }

    public String getUserEmail() {
	return this.userEmail;
    }

    public String getUserName() {
	return this.userName;
    }

    public String getPasswordHash() {
	return this.passwordHash;
    }

    public List<User> getContacts() {
	return this.contacts;
    }

    public void addContact(User u) {
	if (this.contacts == null) {
	    this.contacts = new ArrayList<User>();
	}

	if (!this.contacts.contains(u))
	    this.contacts.add(u);
    }

}
